numseq formatter handling of values like "2.0" which would throw error when trying to convert to int
Like int('2.0') throwing error

ValueError: invalid literal for int() with base 10: '2.0'